
/*
Explores steps required to enter real numbers
convert them to binary and then reconvert them to strings
Looks at the errors generated by this process.
*/



#include "Project_header.h"

int main (void){ 

long LHS, RHS;
char T_array[15];
char dp_ptr;
char expt_10;
char E_ptr;


setup_328_HW;                                                       //see header file"
sei();

while(1){
do{Serial.write("F/f    ");}                                        //User prompt; press F or f to escape
while((isCharavailable(127) == 0));                                 //Waits 1 sec for user response; then resends prompt    
keypress = Serial.read();
if ((keypress  == 'F')||
(keypress  == 'f'))break;}


while(1){

Serial.write("\r\n\r\nFPN from keyboard\t");                          //User enters floating point number (FPN)

sign = positive;                                                      //Default setting
E_ptr = Scientific_num_from_KBD(data_buff, &sign);              //Subroutine echoes keypresses to screen

Serial.write("\r\n");
Serial.write(data_buff);


dp_ptr = 0;
while (data_buff[dp_ptr] != '.')
{if(data_buff[dp_ptr++] > '0')

{dp_ptr = 0;Serial.write ("CD");
while (data_buff[dp_ptr++] != '.');
for (int m = dp_ptr-1; m >= 2; m--)
data_buff[m] = data_buff[m - 1];
data_buff [1] = '.';
dp_location = 1;
expt_10 = dp_ptr - 2;

Serial.write("\r\n");
Serial.write(data_buff); Serial.write ('E'); Serial.write (expt_10 + '0');break;}}

if (data_buff[dp_ptr] == '.')
{expt_10 = 0;Serial.write ("AB");
while ((data_buff[dp_ptr + 1])  == '0'){
{for(int m = dp_ptr + 1; m < 13; m++)data_buff[m] = data_buff[m + 1];}
data_buff[14] = 0;expt_10 -= 1;}
data_buff[dp_ptr] = data_buff[dp_ptr + 1];
data_buff[dp_ptr + 1] = '.';
dp_location = dp_ptr + 1;
expt_10 -= 1;
Serial.write("\r\n");
Serial.write(data_buff);Serial.write ("E-"); Serial.write (expt_10 * -1 + '0');

}


/*LHS = atol(data_buff); 
RHS = atol(data_buff + dp_location + 1);

Serial.write("\r\n");
ltoa(LHS, T_array, 10);Serial.write(T_array);Serial.write('\t');
ltoa(RHS, T_array, 10);Serial.write(T_array);*/
Serial.write("\r\n");

Real_Num_to_FPN();
Serial.write("FPN equivalent\t");







FNP_in_binary_to_PC(FPN);



/********Reverse the proces to recover the real number****************************************************************/

Serial.write ("\r\n\r\nReverse the process\r\n");

FPN_print_out();




Serial.write("\r\n"); }}
